apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: templates
  description: A collection of all templates
spec:
  targets:
    - ./templates/cluster/eks/template.yaml
    - ./templates/cluster/aks/template.yaml
    - ./templates/application/template.yaml
    - ./templates/cluster/deks/template.yaml
    - ./templates/cluster/daks/template.yaml
    - ./templates/fastapi-application/template.yaml
    - https://github.com/backstage/software-templates/blob/main/scaffolder-templates/clean-architecture-app/template.yaml
    - https://github.com/backstage/software-templates/blob/main/scaffolder-templates/create-react-app/template.yaml
    - https://github.com/backstage/software-templates/tree/main/scaffolder-templates/docs-template-cookiecutter/template.yaml
    - https://github.com/backstage/software-templates/blob/main/scaffolder-templates/docs-template/template.yaml
    - https://github.com/backstage/software-templates/blob/main/scaffolder-templates/gitlab-merge-request/template.yaml
    - https://github.com/backstage/software-templates/blob/main/scaffolder-templates/pull-request/template.yaml
    - https://github.com/backstage/software-templates/blob/main/scaffolder-templates/rails-demo/template.yaml
    - https://github.com/backstage/software-templates/blob/main/scaffolder-templates/react-ssr-template/template.yaml
    - https://github.com/backstage/software-templates/blob/main/scaffolder-templates/springboot-grpc-template/template.yaml
